# <center>M1 T02: Dataframes amb Pandas

In [99]:
# Siento no seguir el estándar de importar pandas como "pd", pero creo que vale la pena escribir cuatro letras de más
#   (a cambio de que el código se entienda mejor):
import pandas

# Especifico que no se oculten columnas, para poder analizarlas:
pandas.set_option('display.max_columns', None)

## Exercici 1
Descarrega el data set **Airlines Delay: Airline on-time statistics and delay causes** i carrega’l a un pandas Dataframe. Explora les dades que conté, i queda’t únicament amb les columnes que consideris rellevants.

In [100]:
# Almaceno el archivo csv en un dataframe, y lo imprimo:
airlines_df = pandas.read_csv('./input/DelayedFlights.csv')

airlines_df

,Unnamed: 0,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,TailNum,ActualElapsedTime,CRSElapsedTime,AirTime,ArrDelay,DepDelay,Origin,Dest,Distance,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,0,2008,1,3,4,2003.0,1955,2211.0,2225,WN,335,N712SW,128.0,150.0,116.0,-14.0,8.0,IAD,TPA,810,4.0,8.0,0,N,0,NaN,NaN,NaN,NaN,NaN
1,1,2008,1,3,4,754.0,735,1002.0,1000,WN,3231,N772SW,128.0,145.0,113.0,2.0,19.0,IAD,TPA,810,5.0,10.0,0,N,0,NaN,NaN,NaN,NaN,NaN
2,2,2008,1,3,4,628.0,620,804.0,750,WN,448,N428WN,96.0,90.0,76.0,14.0,8.0,IND,BWI,515,3.0,17.0,0,N,0,NaN,NaN,NaN,NaN,NaN
3,4,2008,1,3,4,1829.0,1755,1959.0,1925,WN,3920,N464WN,90.0,90.0,77.0,34.0,34.0,IND,BWI,515,3.0,10.0,0,N,0,2.0,0.0,0.0,0.0,32.0
4,5,2008,1,3,4,1940.0,1915,2121.0,2110,WN,378,N726SW,101.0,115.0,87.0,11.0,25.0,IND,JAX,688,4.0,10.0,0,N,0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1936753,7009710,2008,12,13,6,1250.0,1220,1617.0,1552,DL,1621,N938DL,147.0,152.0,120.0,25.0,30.0,MSP,ATL,906,9.0,18.0,0,N,0,3.0,0.0,0.0,0.0,22.0
1936754,7009717,2008,12,13,6,657.0,600,904.0,749,DL,1631,N3743H,127.0,109.0,78.0,75.0,57.0,RIC,ATL,481,15.0,34.0,0,N,0,0.0,57.0,18.0,0.0,0.0
1936755,7009718,2008,12,13,6,1007.0,847,1149.0,1010,DL,1631,N909DA,162.0,143.0,122.0,99.0,80.0,ATL,IAH,689,8.0,32.0,0,N,0,1.0,0.0,19.0,0.0,79.0
1936756,7009726,2008,12,13,6,1251.0,1240,1446.0,1437,DL,1639,N646DL,115.0,117.0,89.0,9.0,11.0,IAD,ATL,533,13.0,13.0,0,N,0,NaN,NaN,NaN,NaN,NaN
1936757,7009727,2008,12,13,6,1110.0,1103,1413.0,1418,DL,1641,N908DL,123.0,135.0,104.0,-5.0,7.0,SAT,ATL,874,8.0,11.0,0,N,0,NaN,NaN,NaN,NaN,NaN

In [101]:
# Elimino la columna "Unnamed 0", correspondiente a los índices del dataframe original, que también los exportaron:
del(airlines_df['Unnamed: 0'])

In [102]:
# Compruebo la cantidad de registros y de columnas:
airlines_df.shape

(1936758, 29)

In [103]:
# Compruebo el tipo de datos de cada columna:
airlines_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1936758 entries, 0 to 1936757
Data columns (total 29 columns):
 #   Column             Dtype
---  ------             -----
 0   Year               int64
 1   Month              int64
 2   DayofMonth         int64
 3   DayOfWeek          int64
 4   DepTime            float64
 5   CRSDepTime         int64
 6   ArrTime            float64
 7   CRSArrTime         int64
 8   UniqueCarrier      object
 9   FlightNum          int64
 10  TailNum            object
 11  ActualElapsedTime  float64
 12  CRSElapsedTime     float64
 13  AirTime            float64
 14  ArrDelay           float64
 15  DepDelay           float64
 16  Origin             object
 17  Dest               object
 18  Distance           int64
 19  TaxiIn             float64
 20  TaxiOut            float64
 21  Cancelled          int64
 22  CancellationCode   object
 23  Diverted           int64
 24  CarrierDelay       float64
 25  WeatherDelay       float64
 26  NASDelay           float64
 27  SecurityDelay      float64
 28  LateAircraftDelay  float64
dtypes: float64(14), int64(10), object(5)
memory usage: 428.5+ MB

In [104]:
# Compruebo la cantidad de valores null de cada columna:
airlines_df.isna().sum()

Year                      0
Month                     0
DayofMonth                0
DayOfWeek                 0
DepTime                   0
CRSDepTime                0
ArrTime                7110
CRSArrTime                0
UniqueCarrier             0
FlightNum                 0
TailNum                   5
ActualElapsedTime      8387
CRSElapsedTime          198
AirTime                8387
ArrDelay               8387
DepDelay                  0
Origin                    0
Dest                      0
Distance                  0
TaxiIn                 7110
TaxiOut                 455
Cancelled                 0
CancellationCode          0
Diverted                  0
CarrierDelay         689270
WeatherDelay         689270
NASDelay             689270
SecurityDelay        689270
LateAircraftDelay    689270
dtype: int64

In [105]:
# Los valores null están en columnas importantes, así que decido eliminar todos los registros con valores null:
airlines_df.dropna(axis=0, how='any', inplace=True)

In [106]:
# Compruebo que ya no hay valores null:
airlines_df.isna().sum()

Year                 0
Month                0
DayofMonth           0
DayOfWeek            0
DepTime              0
CRSDepTime           0
ArrTime              0
CRSArrTime           0
UniqueCarrier        0
FlightNum            0
TailNum              0
ActualElapsedTime    0
CRSElapsedTime       0
AirTime              0
ArrDelay             0
DepDelay             0
Origin               0
Dest                 0
Distance             0
TaxiIn               0
TaxiOut              0
Cancelled            0
CancellationCode     0
Diverted             0
CarrierDelay         0
WeatherDelay         0
NASDelay             0
SecurityDelay        0
LateAircraftDelay    0
dtype: int64

In [107]:
# Compruebo que las columnas 'Cancelled', 'Diverted' y 'CancellationCode' ahora tienen un único valor:
print(airlines_df['Cancelled'].unique())
print(airlines_df['Diverted'].unique())
print(airlines_df['CancellationCode'].unique())

[0]
[0]
['N']

In [108]:
# Elimino 4 columnas, que tienen un único valor ("Year" desde el principio, y las demás desde que eliminé los nulls):
airlines_df.drop(['Year','Cancelled','CancellationCode','Diverted'], axis=1, inplace=True)

In [109]:
# También elimino las columnas 'TaxiIn' y 'TaxiOut', que me parecen poco relevantes:
airlines_df.drop(['TaxiIn','TaxiOut'], axis=1, inplace=True)

In [110]:
# Finalmente, actualizo los índices, y vuelvo a imprmir el dataframe:
airlines_df.reset_index(drop=True, inplace=True)

airlines_df

,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,TailNum,ActualElapsedTime,CRSElapsedTime,AirTime,ArrDelay,DepDelay,Origin,Dest,Distance,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,1,3,4,1829.0,1755,1959.0,1925,WN,3920,N464WN,90.0,90.0,77.0,34.0,34.0,IND,BWI,515,2.0,0.0,0.0,0.0,32.0
1,1,3,4,1937.0,1830,2037.0,1940,WN,509,N763SW,240.0,250.0,230.0,57.0,67.0,IND,LAS,1591,10.0,0.0,0.0,0.0,47.0
2,1,3,4,1644.0,1510,1845.0,1725,WN,1333,N334SW,121.0,135.0,107.0,80.0,94.0,IND,MCO,828,8.0,0.0,0.0,0.0,72.0
3,1,3,4,1452.0,1425,1640.0,1625,WN,675,N286WN,228.0,240.0,213.0,15.0,27.0,IND,PHX,1489,3.0,0.0,0.0,0.0,12.0
4,1,3,4,1323.0,1255,1526.0,1510,WN,4,N674AA,123.0,135.0,110.0,16.0,28.0,IND,TPA,838,0.0,0.0,0.0,0.0,16.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1247481,12,13,6,921.0,830,1112.0,1008,DL,1616,N907DE,111.0,98.0,82.0,64.0,51.0,ATL,PBI,545,51.0,0.0,13.0,0.0,0.0
1247482,12,13,6,1552.0,1520,1735.0,1718,DL,1620,N905DE,43.0,58.0,27.0,17.0,32.0,HSV,ATL,151,0.0,0.0,0.0,0.0,17.0
1247483,12,13,6,1250.0,1220,1617.0,1552,DL,1621,N938DL,147.0,152.0,120.0,25.0,30.0,MSP,ATL,906,3.0,0.0,0.0,0.0,22.0
1247484,12,13,6,657.0,600,904.0,749,DL,1631,N3743H,127.0,109.0,78.0,75.0,57.0,RIC,ATL,481,0.0,57.0,18.0,0.0,0.0
1247485,12,13,6,1007.0,847,1149.0,1010,DL,1631,N909DA,162.0,143.0,122.0,99.0,80.0,ATL,IAH,689,1.0,0.0,19.0,0.0,79.0

## Exercici 2
Fes un informe complet del data set:
- Resumeix estadísticament les columnes d’interès

In [111]:
airlines_df[['ArrDelay','DepDelay','CarrierDelay','WeatherDelay',
             'NASDelay','SecurityDelay','LateAircraftDelay']].describe().round(2)

,ArrDelay,DepDelay,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
count,1247486.00,1247486.00,1247486.00,1247486.00,1247486.00,1247486.00,1247486.00
mean,63.29,59.68,19.18,3.70,15.02,0.09,25.30
std,60.75,59.87,43.55,21.49,33.83,2.02,42.05
min,15.00,6.00,0.00,0.00,0.00,0.00,0.00
25%,26.00,24.00,0.00,0.00,0.00,0.00,0.00
50%,43.00,41.00,2.00,0.00,2.00,0.00,8.00
75%,79.00,75.00,21.00,0.00,15.00,0.00,33.00
max,2461.00,2467.00,2436.00,1352.00,1357.00,392.00,1316.00

- Troba quantes dades faltants hi ha per columna

In [112]:
# Ya lo he hecho en el ejercicio 1, y he eliminado todos los nulls (ya no hay ninguno).

- Crea columnes noves (velocitat mitjana del vol, si ha arribat tard o no...)

In [113]:
# Creo la columna 'Velocity', con la velocidad media de cada vuelo:
airlines_df['Velocity'] = (airlines_df['Distance'] / airlines_df['ActualElapsedTime']).round(3)

airlines_df

,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,TailNum,ActualElapsedTime,CRSElapsedTime,AirTime,ArrDelay,DepDelay,Origin,Dest,Distance,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay,Velocity
0,1,3,4,1829.0,1755,1959.0,1925,WN,3920,N464WN,90.0,90.0,77.0,34.0,34.0,IND,BWI,515,2.0,0.0,0.0,0.0,32.0,5.722
1,1,3,4,1937.0,1830,2037.0,1940,WN,509,N763SW,240.0,250.0,230.0,57.0,67.0,IND,LAS,1591,10.0,0.0,0.0,0.0,47.0,6.629
2,1,3,4,1644.0,1510,1845.0,1725,WN,1333,N334SW,121.0,135.0,107.0,80.0,94.0,IND,MCO,828,8.0,0.0,0.0,0.0,72.0,6.843
3,1,3,4,1452.0,1425,1640.0,1625,WN,675,N286WN,228.0,240.0,213.0,15.0,27.0,IND,PHX,1489,3.0,0.0,0.0,0.0,12.0,6.531
4,1,3,4,1323.0,1255,1526.0,1510,WN,4,N674AA,123.0,135.0,110.0,16.0,28.0,IND,TPA,838,0.0,0.0,0.0,0.0,16.0,6.813
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1247481,12,13,6,921.0,830,1112.0,1008,DL,1616,N907DE,111.0,98.0,82.0,64.0,51.0,ATL,PBI,545,51.0,0.0,13.0,0.0,0.0,4.910
1247482,12,13,6,1552.0,1520,1735.0,1718,DL,1620,N905DE,43.0,58.0,27.0,17.0,32.0,HSV,ATL,151,0.0,0.0,0.0,0.0,17.0,3.512
1247483,12,13,6,1250.0,1220,1617.0,1552,DL,1621,N938DL,147.0,152.0,120.0,25.0,30.0,MSP,ATL,906,3.0,0.0,0.0,0.0,22.0,6.163
1247484,12,13,6,657.0,600,904.0,749,DL,1631,N3743H,127.0,109.0,78.0,75.0,57.0,RIC,ATL,481,0.0,57.0,18.0,0.0,0.0,3.787
1247485,12,13,6,1007.0,847,1149.0,1010,DL,1631,N909DA,162.0,143.0,122.0,99.0,80.0,ATL,IAH,689,1.0,0.0,19.0,0.0,79.0,4.253

In [114]:
# Creo la columna 'Delayed', iniciándola con valor 'False' en todos los registros:
airlines_df['Delayed'] = False

In [115]:
# Itero el dataframe, y actualizo el valor de la columna 'Delayed' por 'True', dependiendo de el caso
#   (si el retraso de llegada es mayor al retraso de salida):

for ind in airlines_df.index:
    if airlines_df.at[ind,'ArrDelay'] > airlines_df.at[ind,'DepDelay']:
        airlines_df.at[ind,'Delayed'] = True

airlines_df

,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,TailNum,ActualElapsedTime,CRSElapsedTime,AirTime,ArrDelay,DepDelay,Origin,Dest,Distance,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay,Velocity,Delayed
0,1,3,4,1829.0,1755,1959.0,1925,WN,3920,N464WN,90.0,90.0,77.0,34.0,34.0,IND,BWI,515,2.0,0.0,0.0,0.0,32.0,5.722,False
1,1,3,4,1937.0,1830,2037.0,1940,WN,509,N763SW,240.0,250.0,230.0,57.0,67.0,IND,LAS,1591,10.0,0.0,0.0,0.0,47.0,6.629,False
2,1,3,4,1644.0,1510,1845.0,1725,WN,1333,N334SW,121.0,135.0,107.0,80.0,94.0,IND,MCO,828,8.0,0.0,0.0,0.0,72.0,6.843,False
3,1,3,4,1452.0,1425,1640.0,1625,WN,675,N286WN,228.0,240.0,213.0,15.0,27.0,IND,PHX,1489,3.0,0.0,0.0,0.0,12.0,6.531,False
4,1,3,4,1323.0,1255,1526.0,1510,WN,4,N674AA,123.0,135.0,110.0,16.0,28.0,IND,TPA,838,0.0,0.0,0.0,0.0,16.0,6.813,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1247481,12,13,6,921.0,830,1112.0,1008,DL,1616,N907DE,111.0,98.0,82.0,64.0,51.0,ATL,PBI,545,51.0,0.0,13.0,0.0,0.0,4.910,True
1247482,12,13,6,1552.0,1520,1735.0,1718,DL,1620,N905DE,43.0,58.0,27.0,17.0,32.0,HSV,ATL,151,0.0,0.0,0.0,0.0,17.0,3.512,False
1247483,12,13,6,1250.0,1220,1617.0,1552,DL,1621,N938DL,147.0,152.0,120.0,25.0,30.0,MSP,ATL,906,3.0,0.0,0.0,0.0,22.0,6.163,False
1247484,12,13,6,657.0,600,904.0,749,DL,1631,N3743H,127.0,109.0,78.0,75.0,57.0,RIC,ATL,481,0.0,57.0,18.0,0.0,0.0,3.787,True
1247485,12,13,6,1007.0,847,1149.0,1010,DL,1631,N909DA,162.0,143.0,122.0,99.0,80.0,ATL,IAH,689,1.0,0.0,19.0,0.0,79.0,4.253,True

- Taula de les aerolínies amb més endarreriments acumulats

In [116]:
airlines_df.groupby('UniqueCarrier')['Delayed'].sum().sort_values(ascending=False)

UniqueCarrier
WN    72882
AA    69036
MQ    51490
OO    46991
UA    43553
DL    43220
XE    36454
NW    33800
CO    30203
US    29704
EV    27722
FL    26486
YV    24582
OH    22115
B6    20557
9E    17731
AS    12516
F9     9522
HA     2667
AQ      151
Name: Delayed, dtype: int64

- Quins són els vols més llargs? I els més endarrerits?

In [117]:
# Imprimo el dataframe ordenado por duración del vuelo, de mayor a menor
#   (no he encontrado ningún identificador único de los vuelos, salvo el ID, por eso imprimo todo el dataframe):
airlines_df.sort_values('ActualElapsedTime', ascending=False)

,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,TailNum,ActualElapsedTime,CRSElapsedTime,AirTime,ArrDelay,DepDelay,Origin,Dest,Distance,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay,Velocity,Delayed
963762,9,9,2,1411.0,920,545.0,1215,HA,21,N586HA,1114.0,355.0,1091.0,1050.0,291.0,SEA,HNL,2677,1040.0,0.0,0.0,0.0,10.0,2.403,True
1241037,12,19,5,1407.0,1335,2217.0,1935,CO,15,N67058,790.0,660.0,634.0,162.0,32.0,EWR,HNL,4962,0.0,32.0,130.0,0.0,0.0,6.281,True
766790,7,23,3,1727.0,1645,323.0,2033,DL,151,N6700,776.0,408.0,346.0,410.0,42.0,JFK,SFO,2586,0.0,0.0,368.0,0.0,42.0,3.332,True
923057,8,2,6,1808.0,1335,38.0,1810,CO,15,N68061,750.0,635.0,597.0,388.0,273.0,EWR,HNL,4962,0.0,12.0,115.0,0.0,261.0,6.616,True
889924,8,19,2,1547.0,1230,717.0,2105,HA,28,N597HA,750.0,335.0,733.0,612.0,197.0,HNL,SEA,2677,612.0,0.0,0.0,0.0,0.0,3.569,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
915452,8,31,7,1119.0,1037,1134.0,1102,AS,65,N796AS,15.0,25.0,9.0,32.0,42.0,WRG,PSG,31,0.0,0.0,0.0,0.0,32.0,2.067,False
562806,5,20,2,1227.0,1038,1242.0,1104,AS,65,N647AS,15.0,26.0,9.0,98.0,109.0,WRG,PSG,31,0.0,0.0,0.0,0.0,98.0,2.067,False
238159,2,26,2,1112.0,1013,1127.0,1040,AS,65,N797AS,15.0,27.0,11.0,47.0,59.0,WRG,PSG,31,47.0,0.0,0.0,0.0,0.0,2.067,False
811678,7,2,3,1839.0,1737,1854.0,1801,AS,64,N764AS,15.0,24.0,10.0,53.0,62.0,PSG,WRG,31,0.0,0.0,0.0,0.0,53.0,2.067,False
913223,8,1,5,1811.0,1737,1825.0,1801,AS,64,N763AS,14.0,24.0,7.0,24.0,34.0,PSG,WRG,31,0.0,0.0,0.0,0.0,24.0,2.214,False

In [120]:
# Creo la columna 'TotalDelay', con el retraso de cada vuelo:
airlines_df['TotalDelay'] = airlines_df['ArrDelay'] - airlines_df['DepDelay']

# Imprimo el dataframe ordenado por retraso del vuelo, de mayor a menor
#   (no he encontrado ningún identificador único de los vuelos, salvo el ID, por eso imprimo todo el dataframe):
airlines_df.sort_values('TotalDelay', ascending=False)

,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,TailNum,ActualElapsedTime,CRSElapsedTime,AirTime,ArrDelay,DepDelay,Origin,Dest,Distance,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay,Velocity,Delayed,TotalDelay
963762,9,9,2,1411.0,920,545.0,1215,HA,21,N586HA,1114.0,355.0,1091.0,1050.0,291.0,SEA,HNL,2677,1040.0,0.0,0.0,0.0,10.0,2.403,True,759.0
889924,8,19,2,1547.0,1230,717.0,2105,HA,28,N597HA,750.0,335.0,733.0,612.0,197.0,HNL,SEA,2677,612.0,0.0,0.0,0.0,0.0,3.569,True,415.0
1243284,12,10,3,1955.0,1900,529.0,2159,CO,616,N12318,574.0,179.0,183.0,450.0,55.0,IAH,MSP,1034,0.0,55.0,395.0,0.0,0.0,1.801,True,395.0
1136253,12,10,3,1952.0,1844,320.0,1948,XE,2710,N12934,448.0,64.0,50.0,452.0,68.0,IAH,BTR,253,0.0,16.0,384.0,0.0,52.0,0.565,True,384.0
766790,7,23,3,1727.0,1645,323.0,2033,DL,151,N6700,776.0,408.0,346.0,410.0,42.0,JFK,SFO,2586,0.0,0.0,368.0,0.0,42.0,3.332,True,368.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
928890,8,14,4,329.0,2000,551.0,2359,DL,163,N6712B,322.0,419.0,289.0,352.0,449.0,JFK,SEA,2421,321.0,31.0,0.0,0.0,0.0,7.519,False,-97.0
594463,6,15,7,1244.0,940,1519.0,1420,XE,408,N12563,95.0,220.0,84.0,59.0,184.0,SAN,ABQ,628,59.0,0.0,0.0,0.0,0.0,6.611,False,-125.0
345597,3,9,7,1823.0,1420,2051.0,1910,9E,2029,91469E,148.0,290.0,90.0,101.0,243.0,PIT,ATL,526,0.0,0.0,0.0,0.0,101.0,3.554,False,-142.0
361807,3,8,6,1256.0,1135,1627.0,1737,AA,2093,N3CDAA,211.0,362.0,177.0,1370.0,1521.0,LGA,MIA,1097,50.0,0.0,1289.0,0.0,31.0,5.199,False,-151.0
506197,5,1,4,1302.0,929,1427.0,1355,OO,6595,N924SW,85.0,266.0,70.0,32.0,213.0,SLC,DEN,391,32.0,0.0,0.0,0.0,0.0,4.600,False,-181.0

## Exercici 3
Exporta el data set net i amb les noves columnes a Excel.

In [126]:
# No puedo guardar el archivo con "to_excel", porque supera el tamaño máximo de registros, asi que lo guardo con "to_csv":

airlines_df.to_csv('./output/DelayedFlights_edited.csv', index=False)

---